# Generated by Django 4.0 on 2024-06-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0008_comentario_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacion',
            name='avg_calificacion',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='edificacion',
            name='number_calification',
            field=models.IntegerField(default=0),
        ),
    ]
