# Generated by Django 4.0 on 2024-06-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0009_edificacion_avg_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificacion',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
    ]
