# Generated by Django 4.0 on 2024-06-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0010_alter_edificacion_avg_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edificacion',
            old_name='number_calification',
            new_name='number_calificacion',
        ),
    ]
