# Generated by Django 4.0 on 2024-06-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0011_rename_number_calification_edificacion_number_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True, verbose_name='rating'),
        ),
    ]
